# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configuration-cache = true
# Project
parchment_minecraft_version = 1.20.1
parchment_mappings_version = 2023.09.03
minecraft_version = 1.20.1
minecraft_version_range = [1.20.1]
forge_version = 47.4.10
forge_version_range = [47.1.33,48)
loader_version_range = [47,)
# Mod
mod_id = create_dragons_plus
mod_artifact_id = create-dragons-plus
mod_name = Create: Dragons Plus
mod_license = LGPL-3.0-or-later
mod_version = 1.11.6
mod_group_id = plus.dragons.createdragonsplus
mod_authors = DragonsPlus
mod_description = Library mod for DragonsPlusMinecraft Create-addons.
mod_github = https://github.com/DragonsPlusMinecraft/CreateDragonsPlus
mod_logo = icon.png
# Integrations
enable_dye_depot_integration = true
enable_dyenamics_integration = true
enable_arts_and_crafts_integration = true
enable_create_garnished_integration = true
enable_immersive_engineering_integration = true
# Mod Dependencies
conditional_mixin_version = 0.6.4
flywheel_minecraft_version = 1.20.1
flywheel_version = 1.0.5
vanillin_version = 1.0.0
registrate_version = MC1.20-1.3.3
ponder_version = 1.0.91
create_version = 6.0.8-289
create_version_production = 6.0.8
create_version_range = [6.0.8,6.1.0)
jei_minecraft_version = 1.20.1
jei_version = 15.20.0.106
curios_minecraft_version = 1.20.1
curios_version = 5.3.1
mixin_extras_version = 0.4.1
# Integration Dependencies
dye_depot_version = fyxrF0Kp
dyenamics_version = 5353528
artsandcrafts_version = 8155599
jinxedlib_version = 6630668
create_garnished_version = tO2irH8t
immersive_engineering_version = 6206989
